"""keyd backend for importing, exporting and validating G15 profiles."""

from __future__ import annotations

import configparser
import re
import subprocess
import tempfile
from pathlib import Path

from g15_profile import PROFILE_NAMES, ProfileSet

ALIASES = (
    ("record", "g1"), ("rewind", "g2"), ("phone", "g3"),
    ("iso", "g4"), ("config", "g5"), ("homepage", "g6"),
    ("refresh", "g7"), ("exit", "g8"), ("move", "g9"),
    ("edit", "g10"), ("scrollup", "g11"), ("scrolldown", "g12"),
    ("kpleftparen", "g13"), ("kprightparen", "g14"),
    ("new", "g15"), ("redo", "g16"), ("f13", "g17"),
    ("f14", "g18"), ("f15", "m1"), ("f16", "m2"),
    ("f17", "m3"), ("f18", "mr"),
)


def render(model: ProfileSet) -> str:
    model.validate()
    lines = [
        "# Generated by G15 Profile Editor.",
        "# Logitech G15 v1: G1-G18 with M1-M3 profiles.",
        f"# Profile Name: {model.name.strip()}",
        f"# Keyboard Backlight Level: {model.brightness}",
        "", "[ids]", model.device_id, "", "[global]", "default_layout = m1",
        "", "[aliases]",
    ]
    lines.extend(f"{source} = {alias}" for source, alias in ALIASES)
    lines.extend(["", "[main]", "m1 = setlayout(m1)",
                  "m2 = setlayout(m2)", "m3 = setlayout(m3)", "mr = noop"])
    for profile in PROFILE_NAMES:
        lines.extend(["", f"[{profile}:layout]"])
        for target in PROFILE_NAMES:
            action = "noop" if target == profile else f"setlayout({target})"
            lines.append(f"{target} = {action}")
        lines.append("mr = noop")
        lines.extend(
            f"g{number} = {action.strip()}"
            for number, action in enumerate(model.bindings[profile], start=1)
        )
    return "\n".join(lines) + "\n"


def save(model: ProfileSet, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(render(model), encoding="utf-8")
    temporary.replace(path)


def load(path: Path, brightness: int | None = None) -> ProfileSet:
    text = path.read_text(encoding="utf-8")
    name_match = re.search(r"^# Profile Name: (.+)$", text, re.MULTILINE)
    profile_name = name_match.group(1).strip() if name_match else path.stem
    if brightness is None:
        match = re.search(r"^# Keyboard Backlight Level: ([0-2])$", text, re.MULTILINE)
        brightness = int(match.group(1)) if match else 2
    parser = configparser.ConfigParser(interpolation=None, strict=False,
                                       allow_no_value=True)
    parser.optionxform = str
    parser.read_string(text)
    device_id = next((key for key, value in parser["ids"].items() if value is None), None)
    if device_id is None:
        raw_ids = text.split("[ids]", 1)[1].split("[", 1)[0]
        device_id = next(line.strip() for line in raw_ids.splitlines()
                         if line.strip() and not line.lstrip().startswith("#"))
    bindings = {}
    for profile in PROFILE_NAMES:
        section = parser[f"{profile}:layout"]
        bindings[profile] = [section.get(f"g{number}", "noop")
                             for number in range(1, 19)]
    result = ProfileSet(name=profile_name, device_id=device_id,
                        brightness=brightness, bindings=bindings)
    result.validate()
    return result


def validate(model: ProfileSet, keyd_command: str) -> None:
    temporary_path = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8",
                                         prefix="g15-profile-", delete=False) as temporary:
            temporary.write(render(model))
            temporary_path = Path(temporary.name)
        result = subprocess.run([keyd_command, "check", str(temporary_path)], text=True,
                                capture_output=True, check=False)
        if result.returncode:
            raise ValueError((result.stdout + result.stderr).strip())
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)
