blank_issues_enabled: false
contact_links:
  - name: Sicherheitsproblem privat melden
    url: https://github.com/IT-NWD/G15-Daemon_Linux/security/advisories/new
    about: Bitte mögliche Sicherheitslücken nicht öffentlich beschreiben.
