# G15Daemon-Konfiguration
# Einträge vor dem ersten Abschnitt gehören zum globalen Bereich.
# Dauerhafte Kommentare beginnen mit einem Semikolon (;).

[Global]
Use MR as Cycle Key: Off
; Tastaturbeleuchtung: 0=aus, 1=mittel, 2=maximal
Keyboard Backlight Level: 2

[PLUGIN_LOAD_ORDER]
0: g15plugin_uinput.so
1: g15plugin_clock.so
2: g15plugin_tcpserver.so
TotalPlugins: 3

[PLUGINS]
Linux UINPUT Keyboard Output: Load
Clock: Load
LCDServer: Load

[Keyboard OS Mapping (uinput)]
device: /dev/input/uinput
Lkeys.mapped: 0

[Clock]
24hrFormat: On
ShowDate: Off
Digital: On
